# Generated by Django 4.1.7 on 2023-10-30 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_alter_customuser_email"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
