# Generated by Django 4.1.7 on 2023-10-16 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pybo", "0009_comment_modify_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "대기"),
                    ("approved", "허가"),
                    ("rejected", "반려"),
                    ("on_hold", "보류"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
