# Generated by Django 4.1.6 on 2023-10-30 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pybo", "0010_question_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "대기"),
                    ("approved", "허가"),
                    ("rejected", "반려"),
                    ("holding", "보류"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
