# Generated by Django 4.1.7 on 2023-10-30 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pybo", "0011_alter_question_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="question_hash",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
