# Generated by Django 4.1.7 on 2023-11-06 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pybo", "0013_remove_answer_voter_remove_comment_voter_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="image",
            field=models.ImageField(null=True, upload_to="appname"),
        ),
    ]
