# Generated by Django 4.1.7 on 2023-11-06 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pybo", "0014_question_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="image",
        ),
    ]
