# Generated by Django 4.1.7 on 2023-11-06 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pybo", "0015_remove_question_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="qr_code",
            field=models.ImageField(blank=True, upload_to="static/qrcodes/"),
        ),
    ]
